### PR TITLE
Add line number for excerpt in oss-detect-backdoor

### LINKED ISSUE #449: How to inspect source code without metainfo
I have collected some malicious package (only source code files), but there is no metadata available (the original package may have been delisted from software register). How can I use OSSGadget to inspect these codes?

### PR DESCRIPTION
**Pull request by Flying-Tom**
Add line number for excerpt in oss-detect-backdoor (resolves  #449 )

### CODE REVIEW

**Comment by Flying-Tom** [comment]
> @microsoft-github-policy-service agree

@microsoft-github-policy-service agree

**Comment by gfs** [comment]
@Flying-Tom for the contribution. I'll give this a look today.

**Review by gfs — APPROVED** [review]
LGTM. Thanks for the contribution!

**Pull request merged**
