### PR TITLE
Fix wildcard version NuGet downloads.

### PR DESCRIPTION
**Pull request by jpinz**
This PR fixes: #331

### CODE REVIEW

**Comment by jpinz** [comment]
Writing some tests for this case now.

**Comment by jpinz** [comment]
Fixing tests now, I also realized it was not a good test because as soon as a new version of any of the ones I wrote tests for would break.

**Review by pmalmsten — APPROVED** [review]

**Review by gfs — COMMENTED** [review]
I don't see a code change in here that handles .* versions differently. Can you explain what is fixed?

**Comment by jpinz** [comment]
> I don't see a code change in here that handles .* versions differently. Can you explain what is fixed?

When debugging I realized it wasn't an issue with handling * versions, but it was an issue with the `TypedManager` which only gets used by NuGet. It was trying to enumerate through extracted files every time, even if we weren't extracting the `.nupkg` file. There might be more that I'm forgetting, so I'll go debug and make sure that was all.
Also I found the issue with the `NuGetPackageActions` where when extracting the file it was the extension of the file + `.nupkg` which is incorrect.

**Comment by jpinz** [comment]
> > I don't see a code change in here that handles .* versions differently. Can you explain what is fixed?
> 
> When debugging I realized it wasn't an issue with handling * versions, but it was an issue with the `TypedManager` which only gets used by NuGet. It was trying to enumerate through extracted files every time, even if we weren't extracting the `.nupkg` file. There might be more that I'm forgetting, so I'll go debug and make sure that was all. Also I found the issue with the `NuGetPackageActions` where when extracting the file it was the extension of the file + `.nupkg` which is incorrect.

Just confirmed it yeah, the `PackageDownloader` constructor did successfully add every version to the `PackageVersions = List<PackageURL>` but the `TypedManager.DownloadVersionAsync` is where it was failing because we were trying to assert that we had extracted **every single** artifact we downloaded, even when we didn't specify that we wanted to extract the file we downloaded.

**Pull request merged**
