### PR TITLE
Added toJson to FindPackageSquatResult

### PR DESCRIPTION
**Pull request by jpinz**
For our project, we need to be able to store the squat results in cosmos, which we are doing as a string. 
Having a `toJson` method in the `FindPackageSquatResult` would be helpful. We could do it just on our side, but I thought it made sense to have in the OSSGadget project as well.
Could be `toString` instead of `toJson` if you think that's appropriate, the general premise is the same.
Also now includes a `FromJsonString` to construct a `FindPackageSquatResult` from a json string.

### CODE REVIEW

**Comment by gfs** [comment]
I fixed the pipeline issue for forks. This seems fine.

**Comment by jpinz** [comment]
@gfs I added a FromJsonString as well, otherwise I think this should be good.

**Comment by gfs** [comment]
Trigger pipelines.

**Pull request merged**
