### PR TITLE
Add MultiExtractor NuGet Packaging

### LINKED ISSUE #47: Release MultiExtractor nupkg

### PR DESCRIPTION
**Pull request by daalcant**
Adds packaging and signing MultiExtractor. 
Disables vhdx extraction tests
Removes 'tests' from Release configuration

Closes #47

### CODE REVIEW

**Comment by daalcant** [comment]
@gfs , the vhdx extraction tests broke sometime before this PR. The first failed pipeline run I see is from commit [3e781fa75d948e438668c08be834ed3b98f2f780](https://github.com/microsoft/OSSGadget/commit/3e781fa75d948e438668c08be834ed3b98f2f780).

I disabled the failing tests in this PR. Are we good to open an issue to debug them and continue with this merge? I'd like to get the MultiExtractor package published, but the failing tests are holding up our deployments.

**Comment by daalcant** [comment]
@scovetta , the MultiExtractor package tags and description are currently pretty simple, let me know if you'd like to change them before we push to NuGet.

From MultiExtractor.csproj:
<Description>A recursive multi-format extractor.</Description>
<PackageTags>unzip extract extractor</PackageTags>

**Comment by gfs** [comment]
Yes. Please open a separate issue and you can merge.

**Comment by daalcant** [comment]
Created #88

**Comment by daalcant** [comment]
This should also fix #76

**Pull request merged**
