### PR TITLE
Retarget all projects to .net 5.0 rc

### PR DESCRIPTION
**Pull request by jacobmsft**
.net 5 is production ready.

### CODE REVIEW

**Comment by gfs** [comment]
@jacobmsft You also will need to update the pipeline to use .NET 5.  

Here's an example snippet
```
steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 5.0.x
    performMultiLevelLookup: true
    includePreviewVersions: true # Required for preview versions
```

from https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops

**Review by gfs — CHANGES_REQUESTED** [review]
This needs the pipeline work alongside it.

**Comment by jacobmsft** [comment]
> 
> 
> This needs the pipeline work alongside it.

good point

**Comment by gfs** [comment]
@daalcant can you double check my pipeline work?

**Comment by daalcant** [comment]
@gfs Looks mostly fine to me. I'm not a fan of "Use Pre-Release .NET SDK" defaulting to true. IMO should default to false and be set via the respective parameter. If the team is fine with it then I am too though.

**Comment by gfs** [comment]
Half a dozen of this six of another. I'm fine changing it to be the other way it'll just mean we have to update core pipeline instead of the templates when 5.0 is official released. Either way we need to update it in multiple places.

**Comment by scovetta** [comment]
.NET Core 5 should be GA pretty soon, so I think it's ok to jump on the latest release. We're only telling developers they need to use a release candidate if they want to compile OSS Gadget - the platform-specific releases should work fine.

But I also don't feel super strong about waiting until GA to make this switch.

**Comment by daalcant** [comment]
I'm in favor of moving forward without changes then.

**Review by gfs — APPROVED** [review]

**Pull request merged**
